C Compiler: src/defs.h File Reference
defs.h File Reference
Functions
int main (int argc, char **argv)
main function
char * read (FILE *file)
reads data from stream
struct Symbol * parse (char *data)
parses data into symbols
struct String * compile (struct Symbol *symbols)
creates assembly from symbols
size_t write (FILE *file, struct String *data)
writes data to stream
Function Documentation
int main (int argc, char ** argv)
main function
Parameters
argc The number of command line arguments.
argv An array containing the command line arguments.
Returns
The error level. 0 means no error.
This is executed on startup. It processes C code from the standard input and writes assembly code (i386, GAS syntax) to the standard output.
Definition at line 42 of file main.c.
References compile(), data, parse(), printSymbol(), read(), and write().
{
        FILE* input = stdin;
        FILE* output = stdout;
        // check args for -i/-o flags
        // read the contents of the input
        char* data = read(input);
        if (data == NULL) // no input
        {
                return 1;
        }
        fprintf(stderr, "%s\n", data);
        // parse the file into organized structures
        struct Symbol* symbols = parse(data);
        printSymbol(stderr, symbols, 0);
        // generate assembly
        struct String* assembly = compile(symbols);
        // write to output
        size_t numBytes = write(output, assembly);
        if (numBytes != 0)
        {
                fprintf(stderr, "%i bytes written\n", numBytes);
                return 0;
        }
        else // nothing written
        {
                fprintf(stderr, "Error: no bytes written\n");
                return 1;
        }
}
char* read (FILE * file)
reads data from stream
Parameters
file The input stream
Returns
A buffer containing the contents of the stream.
Reads all content from the given stream until an EOF is reached. The data is stored in a dynamically allocated buffer that is null terminated.
Definition at line 40 of file read.c.
Referenced by main().
{
        char* dest = NULL;
        size_t size = 0;
        const size_t buffer_size = 512;
        char buffer[buffer_size];
        if (file)
        {
                // grab each character and add it to the buffer
                int c = fgetc(file);
                int i = 0;
                while (c != EOF)
                {
                        buffer[i] = (char) c;
                        i++;
                        // if buffer is full, copy it to dest
                        if (i == buffer_size)
{
                                size += buffer_size;
                                dest = realloc(dest, size);
                                memcpy(dest + size - buffer_size, buffer, buffer_size);
                                i = 0;
                        }
                        c = fgetc(file);
                }
                // copy buffer to dest and null terminate
                dest = realloc(dest, size + i + 1);
                memcpy(dest + size, buffer, i);
                dest[size + i] = '\0';
                if (strlen(dest) != 0)
                        return dest;
                else
                        return NULL;
        }
        return NULL;
}
struct Symbol* parse (char * data) read
parses data into symbols
Parameters
data The buffer of data to be translated into symbols.
Returns
A tree of symbols representing the data.
Parses the code in the buffer to create a tree of symbols.
Definition at line 42 of file parse.c.
References combine(), interpret(), printSymbol(), and translate().
Referenced by main().
{
        struct Symbol* symbols = translate(data);
        symbols = interpret(symbols);
        printSymbol(stderr, symbols, 0);
        struct Symbol* tree = combine(symbols);
        return tree;
}
struct String* compile (struct Symbol * symbols) read
creates assembly from symbols
Parameters
symbols Symbolic tree to be converted to assembly.
Returns
A buffer containing the assembly code.
The entire tree of symbols is compiled into assembly. Each line of assembly is stored in its own string structure.
Definition at line 66 of file compile.c.
References addString(), data, getAssembly(), newScope(), newString(), Symbol::next, and VAL.
Referenced by main().
{
        char buffer[512];
        scope = newScope();
        data = newString(0);
        struct String* text = NULL;
        while (symbols)
        {
                if (text == NULL)
                        text = getAssembly(symbols, VAL);
                else
                        addString(text, getAssembly(symbols, VAL));
                symbols = symbols->next;
        }
        // insert data before text
        addString(data, text);
        return data;
}
size_t write (FILE * file, struct String * data)
writes data to stream
Parameters
file The output stream.
data The list of strings that is to be written.
Returns
The number of bytes that were written.
Each string in the list is written consecutively into the given stream.
Definition at line 39 of file write.c.
References String::contents, and String::next.
Referenced by main().
{
        if (file)
        {
                // write to file
                size_t numBytes = 0;
                while (data)
                {
                        // only write if not empty
                        if (data->contents)
                                numBytes += fprintf(file, "%s", data->contents);
                        data = data->next;
                }
                return numBytes;
        }
        return 0;
}