C Compiler: src/scope.c File Reference
scope.c File Reference
#include <stdlib.h>
#include <string.h>
#include "scope.h"
Functions
struct Scope * newScope ()
scope object constructor
void deleteScope (struct Scope *scope)
scope object destructor
void addScope (struct Scope *base, size_t offset)
add new scope to end
int getOffset (struct Scope *scope, int varID)
finds the memory offset of an object within a scope
void addVariable (struct Scope *scope, int id, size_t size)
adds new object to scope
Function Documentation
struct Scope* newScope () read
scope object constructor
Allocates and initializes a new scope object on the heap.
Definition at line 41 of file scope.c.
References Scope::bottom, Scope::next, Scope::offset, and scope.
Referenced by addScope(), compile(), and getAssembly().
{
        struct Scope* scope = malloc(sizeof(struct Scope));
        scope->bottom = 0;
        scope->offset = 0;
        scope->next = NULL;
        return scope;
}
void deleteScope (struct Scope * scope)
scope object destructor
Deletes the given scope.
Definition at line 53 of file scope.c.
Referenced by getAssembly().
{
        if (scope != NULL)
                free(scope);
        return;
}
void addScope (struct Scope * base, size_t offset)
add new scope to end
Allocates and initializes a new scope on the heap and appends it to the end of the given scope.
Definition at line 64 of file scope.c.
References Scope::bottom, newScope(), Scope::next, Scope::offset, and scope.
{
        struct Scope* scope = newScope();
        scope->offset = base->bottom + offset;
        base->next = scope;
}
int getOffset (struct Scope * scope, int varID)
finds the memory offset of an object within a scope
Looks through each scope and finds the offset of the object with the given id.
Definition at line 75 of file scope.c.
References Scope::next, Scope::offset, and Scope::variables.
Referenced by getAssembly().
{
        // for all others, ebp < scopeOffset (more negative)
        int ebp = scope->offset;
        while (scope)
        {
                // if it exists
                if (scope->variables[varID] > 0)
                {
                        return scope->offset - ebp - scope->variables[varID];
                }
                scope = scope->next;
        }
        // variable does not exist
        return -15;
}
void addVariable (struct Scope * scope, int id, size_t size)
adds new object to scope
Adds a new object with the given properties to the curren scope.
Definition at line 96 of file scope.c.
References Scope::bottom, and Scope::variables.
Referenced by getAssembly().
{
        scope->bottom += size;
        scope->variables[id] = scope->bottom;
}