C Compiler: src/string.h File Reference
string.h File Reference
Classes
struct String
a character string
Functions
struct String * newString (size_t size)
string object constructor
struct String * getString (char *array)
string object constructor
void deleteString (struct String *string)
string object destructor
void deleteStringList (struct String *base)
string list destructor
void addString (struct String *dest, struct String *string)
concatenate strings
Function Documentation
struct String* newString (size_t size) read
string object constructor
Parameters
size The size of the buffer to be allocated.
Returns
A pointer to the created string.
Allocates and initializes a new string of a given size.
Definition at line 41 of file string.c.
References String::size.
Referenced by compile(), and getAssembly().
{
        struct String* string = malloc(sizeof(struct String));
        string->size = size;
        if (size > 0)
                string->contents = malloc(size);
        else
                string->contents = NULL;
        string->next = NULL;
        return string;
}
struct String* getString (char * array) read
string object constructor
Parameters
array Contains the string to be created.
Returns
A pointer to the created string.
Allocates and initializes a new string with the given contents.
Definition at line 56 of file string.c.
References String::contents, and String::size.
Referenced by getAssembly().
{
        struct String* string = malloc(sizeof(struct String));
        string->size = strlen(array);
        string->contents = malloc(string->size + 1);
        strcpy(string->contents, array);
        string->contents[string->size] = '\0';
        string->next = NULL;
        return string;
}
void deleteString (struct String * string)
string object destructor
Parameters
string The string to be destroyed.
Destroys the given string.
Definition at line 70 of file string.c.
Referenced by deleteStringList(), and getAssembly().
{
        if (string != NULL)
                free(string);
        return;
}
void deleteStringList (struct String * base)
string list destructor
Parameters
base The string list to be destroyed
Destroys all strings in the given list.
Definition at line 80 of file string.c.
References deleteString(), deleteStringList(), and String::next.
Referenced by deleteStringList().
{
        if (base->next != NULL)
                deleteStringList(base->next);
        deleteString(base);
        return;
}
void addString (struct String * dest, struct String * string)
concatenate strings
Parameters
dest The base string.
string The string to be added to the base string.
Adds string to the end of dest.
Definition at line 91 of file string.c.
References String::next.
Referenced by compile(), and getAssembly().
{
        while (dest->next != NULL)
        {
                dest = dest->next;
        }
        dest->next = string;
        return;
}