C Compiler: src/symbol.h File Reference
symbol.h File Reference
Classes
struct Symbol
a symbol representing a C construct
Enumerations
enum SymbolType {
VARIABLE, STRING, VALUE, TYPE,
DECLARE, PARENTHESES, BRACKET, FUNCTION,
AUTO, BREAK, CASE, CHAR,
CONST, CONTINUE, DEFAULT, DO,
DOUBLE, ELSE, ENUM, EXTERN,
FLOAT, FOR, GOTO, IF,
INT, LONG, REGISTER, RETURN,
SHORT, SIGNED, SIZEOF, STATIC,
STRUCT, SWITCH, TYPEDEF, UNION,
UNSIGNED, VOID, VOLATILE, WHILE,
INCREMENT_POST, DECREMENT_POST, CALL, SUBSCRIPT,
MEMBER, PTR_MEMBER, INCREMENT_PRE, DECREMENT_PRE,
UPLUS, UMINUS, NOT, BNOT,
CAST, DEREFERENCE, ADDRESS, MULTIPLY,
DIVIDE, MODULUS, ADD, SUBTRACT,
LSHIFT, RSHIFT, LESS, LESS_OR_EQUAL,
GREATER, GREATER_OR_EQUAL, EQUAL, NEQUAL,
BAND, BXOR, BOR, AND,
OR, TERNARY_CONDITIONAL, ASSIGN, AADD,
ASUBTRACT, AMULTIPLY, ADIVIDE, AMODULUS,
ALSHIFT, ARSHIFT, ABAND, ABXOR,
ABOR, COMMA, ASTERISK, PLUS,
MINUS, AMPERSAND, INCREMENT, DECREMENT,
QUESTION, COLON, BPAREN, EPAREN,
BBRACK, EBRACK, BBRACE, EBRACE,
SEMICOLON, BLANK
}
Functions
struct Symbol * newSymbol (enum SymbolType type)
symbol object constructor
void deleteSymbol (struct Symbol *symbol)
symbol object destructor
void deleteSymbolList (struct Symbol *base)
symbol tree destructor
void addSymbol (struct Symbol *dest, struct Symbol *symbol)
concatenate symbols
char * operatorString (enum SymbolType operatorID)
string representing an operator
char * keywordString (enum SymbolType keywordID)
string representing a keyword
struct Symbol * reverseSymbol (struct Symbol *root)
reverses the tree
void printSymbol (FILE *out, struct Symbol *symbol, int depth)
prints symbol tree
Enumeration Type Documentation
enum SymbolType
The type of symbol.
Enumerator:
VARIABLE
STRING
VALUE
TYPE
DECLARE
PARENTHESES
BRACKET
FUNCTION
AUTO
BREAK
CASE
CHAR
CONST
CONTINUE
DEFAULT
DO
DOUBLE
ELSE
ENUM
EXTERN
FLOAT
FOR
GOTO
IF
INT
LONG
REGISTER
RETURN
SHORT
SIGNED
SIZEOF
STATIC
STRUCT
SWITCH
TYPEDEF
UNION
UNSIGNED
VOID
VOLATILE
WHILE
INCREMENT_POST
DECREMENT_POST
CALL
SUBSCRIPT
MEMBER
PTR_MEMBER
INCREMENT_PRE
DECREMENT_PRE
UPLUS
UMINUS
NOT
BNOT
CAST
DEREFERENCE
ADDRESS
MULTIPLY
DIVIDE
MODULUS
ADD
SUBTRACT
LSHIFT
RSHIFT
LESS
LESS_OR_EQUAL
GREATER
GREATER_OR_EQUAL
EQUAL
NEQUAL
BAND
BXOR
BOR
AND
OR
TERNARY_CONDITIONAL
ASSIGN
AADD
ASUBTRACT
AMULTIPLY
ADIVIDE
AMODULUS
ALSHIFT
ARSHIFT
ABAND
ABXOR
ABOR
COMMA
ASTERISK
PLUS
MINUS
AMPERSAND
INCREMENT
DECREMENT
QUESTION
COLON
BPAREN
EPAREN
BBRACK
EBRACK
BBRACE
EBRACE
SEMICOLON
BLANK
Definition at line 36 of file symbol.h.
{
        // special stuff
        VARIABLE,
        STRING,
        VALUE,
        TYPE,
        DECLARE,
        PARENTHESES,
        BRACKET,
        FUNCTION,
        // keywords
        AUTO,
        BREAK,
        CASE,
        CHAR,
        CONST,
        CONTINUE,
        DEFAULT,
        DO,
        DOUBLE,
        ELSE,
        ENUM,
        EXTERN,
        FLOAT,
        FOR,
        GOTO,
        IF,
//      INLINE,
        INT,
        LONG,
        REGISTER,
//      RESTRICT,
        RETURN,
        SHORT,
        SIGNED,
        SIZEOF,
        STATIC,
        STRUCT,
        SWITCH,
        TYPEDEF,
        UNION,
        UNSIGNED,
        VOID,
        VOLATILE,
        WHILE,
//      _ALIGNAS,
//      _ALIGNOF,
//      _ATOMIC,
//      _BOOL,
//      _COMPLEX,
//      _GENERIC,
//      _IMAGINARY,
//      _NORETURN,
//      _STATIC_ASSERT,
//      _THREAD_LOCAL,
        // 1 lr
        INCREMENT_POST,
        DECREMENT_POST,
        CALL,
        SUBSCRIPT,
        MEMBER,
        PTR_MEMBER,
//      COMPOUND_LITERAL, // C99
        // 2 rl
        INCREMENT_PRE,
        DECREMENT_PRE,
        UPLUS,
        UMINUS,
        NOT,
        BNOT,
        CAST,
        DEREFERENCE,
        ADDRESS,
//      SIZEOF, // also a keyword?
//      ALIGN, // C11
        // 3 lr
        MULTIPLY,
        DIVIDE,
        MODULUS,
        // 4
        ADD,
        SUBTRACT,
        // 5
        LSHIFT,
        RSHIFT,
        // 6
        LESS,
        LESS_OR_EQUAL,
        GREATER,
        GREATER_OR_EQUAL,
        // 7
        EQUAL,
        NEQUAL,
        // 8
        BAND,
        // 9
        BXOR,
        // 10
        BOR,
        // 11
        AND,
        // 12
        OR,
        // 13 rl
        TERNARY_CONDITIONAL,
        // 14
        ASSIGN,
        AADD,
        ASUBTRACT,
        AMULTIPLY,
        ADIVIDE,
        AMODULUS,
        ALSHIFT,
        ARSHIFT,
        ABAND,
        ABXOR,
        ABOR,
        // 15 lr
        COMMA,
        // only used for parsing
        ASTERISK,
        PLUS,
        MINUS,
        AMPERSAND,
        INCREMENT,
        DECREMENT,
        QUESTION,
        COLON,
        BPAREN,
        EPAREN,
        BBRACK,
        EBRACK,
        BBRACE,
        EBRACE,
        SEMICOLON,
        // placeholders
        BLANK
};
Function Documentation
struct Symbol* newSymbol (enum SymbolType type) read
symbol object constructor
Parameters
type The type of symbol to be created.
Returns
A pointer to the created symbol.
Allocates and initializes a new symbol of the given type.
Definition at line 41 of file symbol.c.
References Symbol::id, Symbol::lhs, Symbol::next, Symbol::rhs, Symbol::third, and Symbol::type.
Referenced by translate().
{
        struct Symbol* symbol = malloc(sizeof(struct Symbol));
        symbol->type = type;
        symbol->id = 0;
        symbol->lhs = NULL;
        symbol->rhs = NULL;
        symbol->third = NULL;
        symbol->next = NULL;
        return symbol;
}
void deleteSymbol (struct Symbol * symbol)
symbol object destructor
Parameters
symbol The symbol to be destroyed.
Destroys the given symbol.
Definition at line 56 of file symbol.c.
Referenced by combine(), deleteSymbolList(), patternContainer(), patternTernary(), and translate().
{
        if (symbol != NULL)
                free(symbol);
        return;
}
void deleteSymbolList (struct Symbol * base)
symbol tree destructor
Parameters
base The symbol tree to be destroyed.
Destroys all symbols in the given tree.
Definition at line 66 of file symbol.c.
References deleteSymbol(), deleteSymbolList(), Symbol::lhs, Symbol::next, and Symbol::rhs.
Referenced by deleteSymbolList().
{
        if (base->next != NULL)
                deleteSymbolList(base->lhs);
                deleteSymbolList(base->rhs);
                deleteSymbolList(base->next);
        deleteSymbol(base);
        return;
}
void addSymbol (struct Symbol * dest, struct Symbol * symbol)
concatenate symbols
Parameters
dest The base symbol.
symbol The symbol to be added to the base symbol.
Adds symbol to the end of dest.
Definition at line 79 of file symbol.c.
References Symbol::next.
Referenced by translate().
{
        while (dest->next != NULL)
        {
                dest = dest->next;
        }
        dest->next = symbol;
        return;
}
char* operatorString (enum SymbolType operatorID)
string representing an operator
Parameters
operatorID The operator to look up.
Returns
The string that represents the given operator.
Gets the string that represents the given operator.
Definition at line 92 of file symbol.c.
References AADD, ABAND, ABOR, ABXOR, ADIVIDE, ALSHIFT, AMODULUS, AMPERSAND, AMULTIPLY, AND, ARSHIFT, ASSIGN, ASTERISK, ASUBTRACT, BBRACE, BBRACK, BLANK, BNOT, BOR, BPAREN, BXOR, COLON, COMMA, DECREMENT, DIVIDE, EBRACE, EBRACK, EPAREN, EQUAL, GREATER, GREATER_OR_EQUAL, INCREMENT, LESS, LESS_OR_EQUAL, LSHIFT, MEMBER, MINUS, MODULUS, NEQUAL, NOT, OR, PLUS, PTR_MEMBER, QUESTION, RSHIFT, SEMICOLON, and TERNARY_CONDITIONAL.
Referenced by translate().
{
        switch (operatorID)
        {
                case TERNARY_CONDITIONAL: return "idk";
                case ALSHIFT: return "<<=";
                case ARSHIFT: return ">>=";
                case EQUAL: return "==";
                case NEQUAL: return "!=";
                case INCREMENT: return "++";
                case DECREMENT: return "--";
                case GREATER_OR_EQUAL: return ">=";
                case LESS_OR_EQUAL: return "<=";
                case PTR_MEMBER: return "->";
                case LSHIFT: return "<<";
                case RSHIFT: return ">>";
                case AND: return "&&";
                case OR: return "||";
                case AADD: return "+=";
                case ASUBTRACT: return "-=";
                case AMULTIPLY: return "*=";
                case ADIVIDE: return "/=";
                case AMODULUS: return "%=";
                case ABAND: return "&=";
                case ABXOR: return "^=";
                case ABOR: return "|=";
                case ASSIGN: return "=";
                case BPAREN: return "(";
                case EPAREN: return ")";
                case BBRACK: return "{";
                case EBRACK: return "}";
                case BBRACE: return "[";
                case EBRACE: return "]";
                case SEMICOLON: return ";";
                case COMMA: return ",";
                case PLUS: return "+";
                case MINUS: return "-";
                case ASTERISK: return "*";
                case DIVIDE: return "/";
                case MEMBER: return ".";
                case GREATER: return ">";
                case LESS: return "<";
                case NOT: return "!";
                case BNOT: return "~";
                case AMPERSAND: return "&";
                case MODULUS: return "%";
                case BXOR: return "^";
                case BOR: return "|";
                case QUESTION: return "?";
                case COLON: return ":";
                case BLANK: return "blank";
                default: return "nonexistent";
        }
}
char* keywordString (enum SymbolType keywordID)
string representing a keyword
Parameters
keywordID The keyword to look up.
Returns
The string that represents the given keyword.
Gets the string that represents the given keyword.
Definition at line 154 of file symbol.c.
References AUTO, BREAK, CASE, CHAR, CONST, CONTINUE, DEFAULT, DO, DOUBLE, ELSE, ENUM, EXTERN, FLOAT, FOR, GOTO, IF, INT, LONG, REGISTER, RETURN, SHORT, SIGNED, SIZEOF, STATIC, STRUCT, SWITCH, TYPEDEF, UNION, UNSIGNED, VOID, VOLATILE, and WHILE.
Referenced by translate().
{
        switch (keywordID)
        {
                case AUTO: return "auto";
                case BREAK: return "break";
                case CASE: return "case";
                case CHAR: return "char";
                case CONST: return "const";
                case CONTINUE: return "continue";
                case DEFAULT: return "default";
                case DO: return "do";
                case DOUBLE: return "double";
                case ELSE: return "else";
                case ENUM: return "enum";
                case EXTERN: return "extern";
                case FLOAT: return "float";
                case FOR: return "for";
                case GOTO: return "goto";
                case IF: return "if";
//              case INLINE: return "inline";
                case INT: return "int";
                case LONG: return "long";
                case REGISTER: return "register";
//              case RESTRICT: return "restrict";
                case RETURN: return "return";
                case SHORT: return "short";
                case SIGNED: return "signed";
                case SIZEOF: return "sizeof";
                case STATIC: return "static";
                case STRUCT: return "struct";
                case SWITCH: return "switch";
                case TYPEDEF: return "typedef";
                case UNION: return "union";
                case UNSIGNED: return "unsigned";
                case VOID: return "void";
                case VOLATILE: return "volatile";
                case WHILE: return "while";
//              case _ALIGNAS: return "_Alignas";
//              case _ALIGNOF: return "_Alignof";
//              case _ATOMIC: return "_Atomic";
//              case _BOOL: return "_Bool";
//              case _COMPLEX: return "_Complex";
//              case _GENERIC: return "_Generic";
//              case _IMAGINARY: return "_Imaginary";
//              case _NORETURN: return "_Noreturn";
//              case _STATIC_ASSERT: return "_Static_assert";
//              case _THREAD_LOCAL: return "_Thread_local";
                default: return "garbage";
        }
}
struct Symbol* reverseSymbol (struct Symbol * root) read
reverses the tree
Parameters
root The symbol tree to reverse.
Returns
A pointer to the reversed tree.
Reverses both the ordering and the arguments of all symbols in the tree. The third argument is left unchanged.
Definition at line 210 of file symbol.c.
References Symbol::lhs, Symbol::next, reverseSymbol(), and Symbol::rhs.
Referenced by patternBinary(), patternUnaryPost(), patternUnaryPre(), and reverseSymbol().
{
        struct Symbol* newRoot = NULL;
        while (root)
        {
                // flip operands
                struct Symbol* lhs = root->lhs;
                root->lhs = root->rhs;
                root->rhs = lhs;
                // reverse operand contents
                root->lhs = reverseSymbol(root->lhs);
                root->rhs = reverseSymbol(root->rhs);
                // flip ordering
                struct Symbol* next = root->next;
                root->next = newRoot;
                newRoot = root;
                root = next;
        }
        return newRoot;
}
void printSymbol (FILE * out, struct Symbol * symbol, int depth)
prints symbol tree
Parameters
out The output stream.
symbol The symbol tree to print.
depth The indent level.
Prints the given symbol tree. It is processes each symbol in the list iteratively, and processes each branch recursively on a new indent level.
Definition at line 236 of file symbol.c.
References ADD, ADDRESS, ASSIGN, ASTERISK, BBRACK, BLANK, BPAREN, BRACKET, CALL, COLON, COMMA, DECLARE, DECREMENT_POST, DEREFERENCE, DIVIDE, EBRACK, EPAREN, EQUAL, FUNCTION, Symbol::id, IF, INCREMENT_POST, Symbol::lhs, MEMBER, MINUS, MULTIPLY, Symbol::name, Symbol::next, PARENTHESES, PLUS, printSymbol(), PTR_MEMBER, QUESTION, RETURN, Symbol::rhs, SEMICOLON, STRING, Symbol::string, SUBSCRIPT, SUBTRACT, TERNARY_CONDITIONAL, TYPE, Symbol::type, VALUE, Symbol::value, VARIABLE, and WHILE.
Referenced by main(), parse(), and printSymbol().
{
        while (symbol)
        {
                int i = 0;
                while (i++ < depth)
                        fprintf(out, "\t");
                switch (symbol->type)
                {
                        case VARIABLE: fprintf(out, "var %i %s ", symbol->id, symbol->name); break;
                        case STRING: fprintf(out, "str %i \"%s\" ", symbol->id, symbol->string); break;
                        case VALUE: fprintf(out, "val %i ", symbol->value); break;
                        case TYPE: fprintf(out, "type "); break;
                        case DECLARE: fprintf(out, "dec "); break;
                        case PARENTHESES: fprintf(out, "paren "); break;
                        case BRACKET: fprintf(out, "brack "); break;
                        case FUNCTION: fprintf(out, "func %s", symbol->name); break;
                        case IF: fprintf(out, "if "); break;
                        case WHILE: fprintf(out, "while "); break;
                        case INCREMENT_POST: fprintf(out, "inc post "); break;
                        case DECREMENT_POST: fprintf(out, "dec post "); break;
                        case CALL: fprintf(out, "call %s ", symbol->name); break;
                        case SUBSCRIPT: fprintf(out, "subscript "); break;
                        case MEMBER: fprintf(out, "member "); break;
                        case PTR_MEMBER: fprintf(out, "ptr member "); break;
                        case DEREFERENCE: fprintf(out, "deref "); break;
                        case ADDRESS: fprintf(out, "addr "); break;
                        case MULTIPLY: fprintf(out, "mult "); break;
                        case DIVIDE: fprintf(out, "div "); break;
                        case ADD: fprintf(out, "add "); break;
                        case SUBTRACT: fprintf(out, "sub "); break;
                        case EQUAL: fprintf(out, "equal "); break;
                        case TERNARY_CONDITIONAL: fprintf(out, "tern cond "); break;
                        case ASSIGN: fprintf(out, "assi "); break;
                        case RETURN: fprintf(out, "ret "); break;
                        case BLANK: fprintf(out, "blank "); break;
                        case PLUS: fprintf(out, "plus "); break;
                        case MINUS: fprintf(out, "minus "); break;
                        case ASTERISK: fprintf(out, "asterisk "); break;
                        case QUESTION: fprintf(out, "question "); break;
                        case COLON: fprintf(out, "colon "); break;
                        case BPAREN: fprintf(out, "bparen "); break;
                        case EPAREN: fprintf(out, "eparen "); break;
                        case BBRACK: fprintf(out, "bbrack "); break;
                        case EBRACK: fprintf(out, "ebrack "); break;
                        case SEMICOLON: fprintf(out, "semicolon "); break;
                        case COMMA: fprintf(out, "comma "); break;
                        default: break;
                }
                fprintf(out, "\n");
                printSymbol(out, symbol->lhs, depth + 1);
                printSymbol(out, symbol->rhs, depth + 1);
                symbol = symbol->next;
        }
        return;
}